version: "3.3"

services:
    db:
         image: mysql:latest
         restart: always
         environment:
             MYSQL_DATABASE: g4database
             MYSQL_ROOT_PASSWORD: pass
         expose:
          - 3306

    app:
        image: app
        restart: always
        links:
          - db
        depends_on:
          - db
        expose:
        - 8443
        ports:
          - 8443:8443
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/g4database?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

