version: "3"

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: g4database
            MYSQL_USER: root
            MYSQL_PASSWORD: pass
    app:
        # replace username/repo:tag with your name and image details
        image: christiantaidi/daw_citas:0.0.2
        restart: always
        links:
            - db
        depends_on:
            - db
        ports:
            - "8080:8443"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db/g4database?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

