version: "3"

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: 
            MYSQL_DATABASE: 
            MYSQL_USER: 
            MYSQL_PASSWORD: 
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        restart: always
        links:
            - db
        depends_on:
            - db
        ports:
            - "8080:8443"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db/daw_quotes?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            SPRING_DATASOURCE_USERNAME: 
            SPRING_DATASOURCE_PASSWORD: 
