version: "3"

services:
    db:
         image: mysql
         restart: always
         environment:
             MYSQL_ROOT_HOST: 127.0.0.1
             MYSQL_ROOT_PASSWORD: pass
             MYSQL_USER: user
             MYSQL_PASSWORD: pass
         expose:
           - 3306
         ports:
           - 127.0.0.1:3306:8080
    app:
        image: christiantaidi/daw_cita:0.1.1
        restart: always
        links:
          - db
        ports:
          - 8080:8080
